All Done PR
itsec-labs/dotnet-1 pull request #10
Opened 2022-03-04 16:24 UTC by hoangnv123

Нгуен Ван Хоанг 6311

2022-03-05 16:34 UTC, navna requested changes
Замечания по всему проекту целиком:
1. **Удалить все бинарные и вспомогательные файлы, которым не место в системе контроля версий!**
2. Пространство имён `Lab1cs` переименовать в более адекватное `Lab1` (все соответствующие файлы и директории также переименовать).
3. Все `using` упорядочить, неиспользуемые удалить (это делается автоматом через пункт меню в IDE).

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Commands/CompareTwoFigure.cs
> +            return 0;
Вместо стандартного `Console` вы должны использовать средства `SpectreConsole` для контроля ввода и вывода. Если не можете сами разобраться в документации библиотеки - смотрите видео Николая Викторовича.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Commands/FigureCommands.cs
> +                "Cylinder" => new Cylinder(1, 2, 3, 5, 10),
А почему вы решили, что параметры фигур пользователь не должен указывать? Все параметры запрашивать у пользователя.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Commands/RemoveFigure.cs
> +            return 0;
Аналогичная ошибка. Используйте `SpectreConsole`.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Cylinder.cs
> +        public double pi = 3.14;
Удалить. Используйте стандартный `Math.PI`.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Cylinder.cs
> +        public Point point { get; set; }
1. Нарушение правил именования.
2. Название бессмысленно. И по типу понятно, что это точка. А что за точка-то?

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Cylinder.cs
> +        public double radius;
Публичных полей быть не должно. Используйте readonly-свойство.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Cylinder.cs
> +        public double height;
Публичных полей быть не должно.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Cylinder.cs
> +            height = 0;
Полностью бессмысленное тело. По умолчанию и так всё по нулям будет. Оставить тело пустым.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Cylinder.cs
> +        }
Зачем такая декомпозиция входных параметров? Удалить этот конструктор вообще.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Cylinder.cs
> +        public Cylinder(Point point1, double r, double h)
Неадекватное название параметра `point1`.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Cylinder.cs
> +        public override double acreage()
Нарушение правил именования.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Cylinder.cs
> +        public override double volume()
Нарушение правил именования.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Cylinder.cs
> +            }
Неоправданное усложнение кода. Смотрите, как было на лекциях.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Figure.cs
> +        public abstract double acreage();
Нарушение правил именования.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Figure.cs
> +        public abstract double volume();
Нарушение правил именования.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Globular.cs
> +    public class Globular : Figure
Неадекватное название. Используйте `Sphere`.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Globular.cs
> +        public double pi = 3.14;
Удалить. Использовать константу из стандартной библиотеки.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Globular.cs
> +        public double radius;
Нарушение правил именования.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Globular.cs
> +            radius = 0;
Бессмысленное тело.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Globular.cs
> +        }
Удалить.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Globular.cs
> +        public Globular(Point point, double r)
Неадекватное название параметра `point`.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Globular.cs
> +        public override double acreage()
Нарушение правил именования.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Globular.cs
> +        public override double volume()
Нарушение правил именования.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Globular.cs
> +            }
Неоправданное усложнение. Смотрите примеры с лекций.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Point.cs
> +        public double Z;
Публичных полей быть не должно. Сделайте всё иммутабельными свойствами.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Rectangular.cs
> +        public double B => Math.Abs(Point1.Y - Point2.Y);
Неадекватные названия и нарушения правил именования.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Rectangular.cs
> +        }
Удалить.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Rectangular.cs
> +        public override double acreage()
Нарушение правил именования.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Rectangular.cs
> +        public override double volume()
Нарушение правил именования.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Model/Rectangular.cs
> +            }
Неоправданное усложнение. Смотрите примеры с лекций.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Reposity/FigureRepository.cs
> +        private List<Figure> figure;
Нарушение правил именования (как минимум: несогласованность с `TypeResolver`).

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Reposity/FigureRepository.cs
> +        public void AddFigure(Figure _figure)
Нарушение правил именования аргумента.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Reposity/FigureRepository.cs
> +        }
Какое отношение сравнение фигур имеет к репозиторию/хранилищу? Никакого! Удалить. Данный код должен быть в более адекватном месте.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Reposity/FigureRepository.cs
> +        }
Какое отношение вывод на экран имеет репозиторию/хранилищу? Никакого! Удалить. Данный код должен быть в более адекватном месте.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Reposity/IFigureRepository.cs
> +namespace Lab1cs.Reposity
`Reposity` - такого слова в английском нет. Пользуйтесь, пожалуйста, словарём.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Reposity/IFigureRepository.cs
> +        void AddFigure(Figure _figure);
Нарушение правил именования.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Reposity/IFigureRepository.cs
> +        void PrintScreen();
Этому методу не место в интерфейсе хранилища. Удалить.

2022-03-05 16:34 UTC, navna commented on sourcecode/Lab1cs/Lab1cs/Reposity/IFigureRepository.cs
> +        bool CompareFigure(int x, int y);
Этому методу не место в интерфейсе хранилища. Удалить.

2022-03-18 17:49 UTC, navna requested changes
1. Нет файла проекта.
2. Методы отделяются от других методов, свойств и полей пустой строкой.

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/CompareTwoFigure.cs
> +        }
Что за бред в 20 строчек?
1. Цикл по i, которая не используется.
2. А если новую фигуру добавить, вы что, потом вспомните, что вам ещё эту лапшу доправить надо, иначе всё перестанет работать?
3. Удалить этот метод вообще. Если классы написаны правильно, то сравнение производится в одну строку `figures[x].Equals(figures[y])`. В отдельном методе нет никакого смысла.

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/CompareTwoFigure.cs
> +    public class CompareTwoFigure : Command<CompareTwoFigure.CompareFigureCommand>
CompareFigure**s**

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/FigureCommands.cs
> +            _figureRepository.AddFigure(f);
Если `f == null`, то `null` добавляется в репозиторий?

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/FigureCommands.cs
> +        }
Полная каша в названиях и даже типах!

Правильный шаблон:
```
public class SomeCommand: Command<SomeCommand.SomeCommandSettings>
{
    public class SomeCommandSettings: CommandSettings
    {
    }
}
```

**Данный шаблон применить ко всем командам.**

Текущую команду переименовать в `AddFigure*` (Some -> AddFigure).

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/PrintListFigure.cs
> +        }
Полная каша в названиях и даже типах!
См. аналогичные замечания в файле `FigureCommands`.
Переименовать в `PrintFigures*`.

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/RemoveFigure.cs
> +        }
Полная каша в названиях и даже типах!
См. аналогичные замечания в файле `FigureCommands`.
Переименовать в `RemoveFigure*`.

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/RemoveFigure.cs
> +            Console.Write("Index = ");
Использовать `AnsiConsole`.

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/ClearAllFigure.cs
> +        }
Полная каша в названиях и даже типах!
См. аналогичные замечания в файле `FigureCommands`.
Переименовать в `ClearFigures*`.

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Model/Cylinder.cs
> +        public readonly double pi = Math.PI;
Are you kidding? Удалить! Используйте непосредственно `Math.PI` везде, где нужно значение константы.

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Model/Cylinder.cs
> +        public Point center { get; set; }
Нарушение правил именования.

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Model/Cylinder.cs
> +        }
??? Удалить все поля и оставить только автоимплементируемые свойства.

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Model/Figure.cs
> +        public abstract double volume();
1. Нарушение правил именования.
2. Название метода должно содержать глагол.

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Model/Point.cs
> +        }
Всё удалить и оставить только два (три?) **автоимплементируемых свойства** X, Y (Z?).

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Model/Rectangular.cs
> +        }
Неадекватные названия.
Оставить только три автоимплементируемых свойства и назвать их адекватно, например, `BaseLeftTop`, `BaseRightBottom` и `Depth`.
Вычисляемые свойства назвать `Width` (разность X) и `Height` (разность Y).

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Model/Sphere.cs
> +        public readonly double pi = Math.PI;
1. Все поля убрать.
2. `pi` убрать.
3. Радиус сделать автоимплементируемым свойством.

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Repository/IFigureRepository.cs
> +        void AddFigure(Figure _figure);
1. Переименовать просто в `Add`.
2. Нарушение правил именования аргумента.

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Repository/IFigureRepository.cs
> +        List<Figure> getFigure();
1. Нарушение правил именования.
2. Сделать во множественном числе: `GetFigures`.

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Repository/IFigureRepository.cs
> +        void ClearAllFigure();
Переименовать просто в `Clear`.

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Repository/IFigureRepository.cs
> +        void RemoveFigure(int index);
Переименовать в `RemoveAt`

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Repository/FigureRepository.cs
> +        private List<Figure> figure;
Нарушение правил именования.
Неадекватное название. Почему **коллекция** фигур называется **фигурой**?

2022-03-18 17:49 UTC, navna commented on sourcecode/Lab1/Lab1/Repository/FigureRepository.cs
> +        public void AddFigure(Figure _figure)
Нарушение правил именования.

2022-03-21 05:25 UTC, navna requested changes
1. Вы, смотрю, мазохист, если каждый раз коммитите и удаляете бинарники вручную. Где `.gitignore`?
2. Почему `MinRectangular` не вынесен в базовый класс `Figure`? Попутно переименовать его в `GetBoundingBox`.

2022-03-21 05:25 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/ClearAllFigure.cs
> +    public class ClearFiguresCommand : Command<ClearFiguresCommand.ClearFiguresCommandSettings>
Несоответствие названия файла и имени класса.

2022-03-21 05:25 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/CompareFigures.cs
> +    public class CompareFiguresCommand : Command<CompareFiguresCommand.CompareFiguresCommandSettings>
Несоответствие названия файла и имени класса.

2022-03-21 05:25 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/CompareFigures.cs
> +            var y = AnsiConsole.Ask<int>("[green]Index 2 = [/]");
Неадекватные названия. Переименовать в `firstIndex` и `secondIndex`.

2022-03-21 05:25 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/FigureCommands.cs
> +    public class AddFigureCommand : Command<AddFigureCommand.AddFigureCommandSettings>
Несоответствие названия файла и имени класса.

2022-03-21 05:25 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/PrintListFigure.cs
> +    public class PrintFiguresCommand : Command<PrintFiguresCommand.PrintFiguresCommandSettings>
Несоответствие названия файла и имени класса.

2022-03-21 05:25 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/PrintListFigure.cs
> +            var figure = _figureRepository.GetFigures();
Неадекватное название. Почему **список фигур** вы называете **фигурой**?

2022-03-21 05:25 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/RemoveFigure.cs
> +    public class RemoveFigureCommand : Command<RemoveFigureCommand.RemoveFigureCommandSettings>
Несоответствие названия файла и имени класса.

2022-03-21 05:25 UTC, navna commented on sourcecode/Lab1/Lab1/Model/Cylinder.cs
> +        public Point Center { get; set; }
Почему здесь `set`, когда у других свойств `init`?

2022-03-21 05:25 UTC, navna commented on sourcecode/Lab1/Lab1/Model/Figure.cs
> +
Лишняя пустая строка.

2022-03-21 05:25 UTC, navna commented on sourcecode/Lab1/Lab1/Model/Sphere.cs
> +        public Point Center { get; set; }
Почему здесь `set`, а у другого свойства `init`?

2022-03-21 05:25 UTC, navna commented on sourcecode/Lab1/Lab1/Model/Sphere.cs
> +            return 4 / 3 * Math.PI * Radius * Radius * Radius;
Вы проверяли эту формулу?

2022-03-21 05:25 UTC, navna commented on sourcecode/Lab1/Lab1/Repository/FigureRepository.cs
> +            var XmlSelializer = new XmlSerializer(typeof(List<Figure>));
Нарушение правил именования.

2022-03-21 05:25 UTC, navna commented on sourcecode/Lab1/Lab1/Repository/FigureRepository.cs
> +            var XmlSelializer = new XmlSerializer(typeof(List<Figure>));
Нарушение правил именования.

2022-03-21 05:25 UTC, navna commented on sourcecode/Lab1/Lab1/Repository/FigureRepository.cs
> +        private List<Figure> ListFigures;
Нарушение правил именования.

2022-03-28 05:30 UTC, navna requested changes

2022-03-28 05:30 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/AddFigureCommand.cs
> +            else
Пустую строку перед else удалить.

2022-03-28 05:30 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/AddFigureCommand.cs
> +                _ => null
А switch может гипотетически попасть на `null`? Если нет, то вместо возврата `null` лучше кидайте исключение. И дальнейшая проверка на null вообще не будет нужна.

2022-03-28 05:30 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/CompareFiguresCommand.cs
> +            var y = AnsiConsole.Ask<int>("[green]secondIndex = [/]");
1. Неадекватные названия `x` (варианты: `firstIndex` или `lhsIndex`), `y`.
2. Опечатка в первой строке (`fist`?)

2022-03-28 05:30 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/GetSumAreaCommand.cs
> +            var _listFigures = _figureRepository.GetFigures();
Нарушение правил именования.

2022-03-28 05:30 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/PrintFiguresCommand.cs
> +            var _listFigures = _figureRepository.GetFigures();
Нарушение правил именования.

2022-03-28 05:30 UTC, navna commented on sourcecode/Lab1/Lab1/Model/Cylinder.cs
> +            new Point(Center.X + Radius, Center.Y + Radius, Center.Z), Height);
Нет выравнивания.

2022-03-28 05:30 UTC, navna commented on sourcecode/Lab1/Lab1/Commands/AddFigureCommand.cs
> +                     .AddChoices("Rectangular", "Sphere", "Cylinder"));
Неадекватное выравнивание.

2022-03-28 05:30 UTC, navna commented on sourcecode/Lab1/Lab1/Model/Cylinder.cs
> +            return Center.Equals(cylinder.Center) && Radius == cylinder.Radius && Height == cylinder.Height;
Определите для `Point` оператор `==` и используйте его.

2022-03-28 05:30 UTC, navna commented on sourcecode/Lab1/Lab1/Model/Rectangular.cs
> +            return BaseLeftTop.Equals(rec.BaseRightBottom) && BaseRightBottom.Equals(rec.BaseRightBottom) && Depth == rec.Depth;
Определите для `Point` оператор `==` и используйте его.

2022-03-28 05:30 UTC, navna commented on sourcecode/Lab1/Lab1/Model/Sphere.cs
> +            new Point(Center.X + Radius, Center.Y + Radius, Center.Z), 2 * Radius);
Нет выравнивания.

2022-03-28 05:30 UTC, navna commented on sourcecode/Lab1/Lab1/Model/Sphere.cs
> +            return Center.Equals(sphere.Center) && Radius == sphere.Radius;
Определите для `Point` оператор `==` и используйте его.

2022-03-28 05:30 UTC, navna commented on sourcecode/Lab1/Lab1/Repository/FigureRepository.cs
> +        public void Add(Figure NewFigure)
Нарушение правил именования аргумента.

2022-03-28 05:30 UTC, navna commented on sourcecode/Lab1/Lab1/Repository/IFigureRepository.cs
> +        void Add(Figure NewFigure);
Нарушение правил именования аргумента.

2022-04-07 15:28 UTC, navna requested changes
Вас жизнь чему-нибудь учит?

Вот замечание ещё с первого ревью от 5 марта:
**Удалить все бинарные и вспомогательные файлы, которым не место в системе контроля версий!**
Оно не исправлено.

Вот замечание с последнего ревью. Оно тоже не исправлено.
https://github.com/itsec-labs/dotnet-1/pull/10#discussion_r836063997

Кроме того, ваше решение **вообще не открывается**. Уж молчу о том, что даже если бы оно и открылось, то не скомпилировалось (см. замечание по коду далее).

Знаете, когда вы просите преподавателя потратить время и проверить ваш код, который вы даже элементарно не то, что проверить (!), а даже скомпилировать (!!) не могли, то как прикажете на это реагировать?

2022-04-07 15:28 UTC, navna commented on sourcecode/Lab1/Lab1/Repository/FigureRepository.cs
> +        }
Скажите, а как вы проверяли этот код? Он ведь даже компилиться не должен...

2022-04-11 18:22 UTC, hoangnv123 commented on sourcecode/Lab1/Lab1/Model/Cylinder.cs
> +            return Center.Equals(cylinder.Center) && Radius == cylinder.Radius && Height == cylinder.Height;
Я Вас не очень понял. Почему нам нужен определить для Point оператор == ? у нас уже есть переопределение метода Equals. И еще в Point полей Radius  и Height нет.

2022-04-16 14:56 UTC, navna requested changes
Замечания не исправлены.

2022-04-16 15:16 UTC, hoangnv123 commented
еще 3 замечания не исправлены. я Вам оставил сообщение но видимо вы не видели. Замечания : Определите для Point оператор == и используйте его. я не совсем понял, зачем нам нужно определить  для Point оператор == ? у нас уже есть переопределение метода Equals в классе Point. а остальные замечания исправлены.

2022-04-17 19:01 UTC, navna commented
### Point

Потому что это структура, а для неё лучше использовать операторы ==/!=. А перегружать Equals для структуры вообще смысла нет, чем вас стандартный не устраивает, который почленно всё сравнивает?

> И еще в Point полей Radius и Height нет.

Это вообще к чему? Их там и не должно быть.

### Нет файла проекта

[Ревью от 18 марта:](https://github.com/itsec-labs/dotnet-1/pull/10#pullrequestreview-914642564)

> 1. Нет файла проекта.

[Ревью от 7 апреля:](https://github.com/itsec-labs/dotnet-1/pull/10#pullrequestreview-935259394)

> Кроме того, ваше решение **вообще не открывается**.

2022-04-19 09:42 UTC, hoangnv123 commented
у меня решение открывается нормально. не знаю почему у вас не получилось открыть решение. если Вы снова не можете открыть мое решение, то завтра в среду могу вам показать на занятие.

2022-04-19 18:25 UTC, navna commented
Вы файл проекта добавили только в этом [коммите](https://github.com/itsec-labs/dotnet-1/pull/10/commits/edf9ebcd55692da85fe2a851d7eaac1d6fed0704). И у вас ещё хватает наглости говорить
> не знаю почему у вас не получилось открыть решение

2022-04-20 05:54 UTC, navna requested changes
В коде у вас используются nullable-ссылки, но в файле проекта они не включены. Как вы это объясните? Вы уверены, что это вообще ваш код? Ну, это риторический вопрос.

По существу:
1. Включить поддержку nullable на уровне проекта.
2. Исправить все предупреждения. При сборке/пересборке проекта не должно быть ни одного предупреждения от компилятора. Сейчас их 9 штук.

2022-04-21 12:34 UTC, closed without merging