Лабораторная работа 1. Вариант 1. Беседина 6312
itsec-labs/dotnet-1 pull request #11
Opened 2022-03-05 03:54 UTC by lbesedka

2022-03-05 16:12 UTC, lbesedka commented
``

2022-03-06 08:36 UTC, kolyanch requested changes

2022-03-06 08:36 UTC, kolyanch commented on src/PromProg1/PromProg1/Commands/AddFigureCommand.cs
> +            var a = 0;
Плохое именование переменных

2022-03-06 08:36 UTC, kolyanch commented on src/PromProg1/PromProg1/Commands/AddFigureCommand.cs
> +        public AddFigureCommand(IFigureRepository _figureRepository)
Нарушение правил именования аргументов

2022-03-06 08:36 UTC, kolyanch commented on src/PromProg1/PromProg1/Commands/CompareCommand.cs
> +        public CompareCommand(IFigureRepository _figureRepository)
Нарушение правил именования

2022-03-06 08:36 UTC, kolyanch commented on src/PromProg1/PromProg1/Commands/DeleteAllCommand.cs
> +        }
Нарушение правил именования

2022-03-06 08:36 UTC, kolyanch commented on src/PromProg1/PromProg1/Commands/DeleteCommand.cs
> +            figureRepository = _figureRepository;
Нарушение правил именования

2022-03-06 08:36 UTC, kolyanch commented on src/PromProg1/PromProg1/Commands/SumCommands.cs
> +            figureRepository = _figureRepository;
Нарушение правил именования

2022-03-06 08:36 UTC, kolyanch commented on src/PromProg1/PromProg1/Commands/TableCommand.cs
> +            figureRepository = controller;
Нарушение правил именования. Почему в данном случае аргумент называется controller?

2022-03-06 08:36 UTC, kolyanch commented on src/PromProg1/PromProg1/Repositories/IFigureRepository.cs
> +        void AddTriangle(int index, Point A, Point B, Point C);
Нарушение правил именования аргументов и свойств

2022-03-06 08:36 UTC, kolyanch commented on src/PromProg1/PromProg1/Model/Triangle.cs
> +                Vertex.Max(arr_vertexes => arr_vertexes.Y)));
Нарушение правил именования

2022-03-06 08:36 UTC, kolyanch commented on src/PromProg1/PromProg1/Model/Triangle.cs
> +            Vertex = new Point[0];
Лучше использовать Array.Empty<Point>()

2022-03-07 06:45 UTC, kolyanch requested changes

2022-03-07 06:45 UTC, kolyanch commented on src/PromProg1/PromProg1/Commands/AddFigureCommand.cs
> +            while (exit != -1)
А почему бы данную переменную не сделать типом bool?

2022-03-07 06:45 UTC, kolyanch commented on src/PromProg1/PromProg1/Commands/AddFigureCommand.cs
> +                            break;
Лишний код

2022-03-07 06:45 UTC, kolyanch commented on src/PromProg1/PromProg1/Commands/CompareCommand.cs
> +                AnsiConsole.Write("\nPerimeteris larger for the element with the index " + _figureRepository.ComparePerimeter(index1, index2));
Perimeteris - не хватает пробела

2022-03-07 07:17 UTC, kolyanch approved these changes

2022-03-07 07:22 UTC, closed without merging