Думаю, что все сделано
itsec-labs/dotnet-1 pull request #12
Opened 2022-03-05 10:10 UTC by Divanchik

Шепляков Дмитрий 6312

2022-03-06 08:38 UTC, kolyanch requested changes
Исключите бинарные файлы из пулл-реквеста

2022-03-06 11:31 UTC, Divanchik commented
Убрал, запрашиваю code review @kolyanch

2022-03-07 07:14 UTC, kolyanch requested changes

2022-03-07 07:14 UTC, kolyanch commented on Lab1/Matrix/BufferedMatrix.cs
> +            set {A[y * Height + x] = value;}
Используйте expression body также как в методе get

2022-03-07 07:14 UTC, kolyanch commented on Lab1/Matrix/BufferedMatrix.cs
> +        public BufferedMatrix(int H, int W)
Нарушение правил именования аргументов метода

2022-03-07 07:14 UTC, kolyanch commented on Lab1/Matrix/BufferedMatrix.cs
> +            Height = Int32.Parse(elem.Attribute("height").Value);
Используйте для типов ключевое слово, в данном случае int и ниже double

2022-03-07 07:14 UTC, kolyanch commented on Lab1/Matrix/BufferedMatrix.cs
> +            if (obj.GetType() != this.GetType())
this в данном случае не нужен

2022-03-07 07:14 UTC, kolyanch commented on Lab1/Matrix/BufferedMatrix.cs
> +            return tmp;
Не используйте именование переменных типа tmp

2022-03-07 07:14 UTC, kolyanch commented on Lab1/Matrix/Matrix.cs
> +        public override int GetHashCode() => base.GetHashCode();
Зачем нужны эти два override?

2022-03-07 07:14 UTC, kolyanch commented on Lab1/Matrix/SparseMatrix.cs
> +            return tmp;
Не используйте именование переменных типа tmp

2022-03-07 07:14 UTC, kolyanch commented on Lab1/Matrix/SparseMatrix.cs
> +            }
Используйте для типов ключевое слово, в данном случае int и ниже double

2022-03-07 07:14 UTC, kolyanch commented on Lab1/Repository/Repository.cs
> +        private List<AbstractMatrix> data;
Нарушение правил именования полей класса

2022-03-07 07:14 UTC, kolyanch commented on Lab1/Repository/Repository.cs
> +        public AbstractMatrix this[int index] { get => data[index]; }
Используйте expression body

2022-03-07 07:14 UTC, kolyanch commented on Lab1/Repository/Repository.cs
> +            { AnsiConsole.WriteException(e); }
Лучше скобки оставить на новой строке, сейчас странно смотрится код

2022-03-07 07:14 UTC, kolyanch commented on Lab1/Repository/Repository.cs
> +                tempTable.AddRow(new[] { "[red]-[/]", "[red]-[/]" });
Используйте перегрузку метода AddRow с params

2022-03-07 10:36 UTC, Divanchik commented on Lab1/Commands/AddMatrixCommand.cs
> +        private IMatrixRepository _data;
есть

2022-03-07 10:51 UTC, Divanchik commented on Lab1/Commands/MinNormCommand.cs
> +            AnsiConsole.Write(new Panel($"{minInd} {minMat.ToString()}"));
есть

2022-03-07 10:52 UTC, Divanchik commented on Lab1/Matrix/BufferedMatrix.cs
> +            set {A[y * Height + x] = value;}
есть

2022-03-07 10:58 UTC, Divanchik commented on Lab1/Matrix/BufferedMatrix.cs
> +        public BufferedMatrix(int H, int W)
есть

2022-03-07 10:59 UTC, Divanchik commented on Lab1/Matrix/BufferedMatrix.cs
> +            Height = Int32.Parse(elem.Attribute("height").Value);
есть

2022-03-07 11:04 UTC, Divanchik commented on Lab1/Matrix/BufferedMatrix.cs
> +            return tmp;
есть

2022-03-07 11:04 UTC, Divanchik commented on Lab1/Matrix/Matrix.cs
> +        public override int GetHashCode() => base.GetHashCode();
есть

2022-03-07 11:06 UTC, Divanchik commented on Lab1/Matrix/SparseMatrix.cs
> +            return tmp;
есть

2022-03-07 11:08 UTC, Divanchik commented on Lab1/Matrix/SparseMatrix.cs
> +            }
есть

2022-03-07 11:10 UTC, Divanchik commented on Lab1/Repository/Repository.cs
> +        private List<AbstractMatrix> data;
есть

2022-03-07 11:11 UTC, Divanchik commented on Lab1/Repository/Repository.cs
> +        public AbstractMatrix this[int index] { get => data[index]; }
есть

2022-03-07 11:12 UTC, Divanchik commented on Lab1/Repository/Repository.cs
> +            { AnsiConsole.WriteException(e); }
есть

2022-03-07 11:16 UTC, Divanchik commented on Lab1/Repository/Repository.cs
> +                tempTable.AddRow(new[] { "[red]-[/]", "[red]-[/]" });
есть

2022-03-07 11:18 UTC, Divanchik commented
Думаю я исправил все недочеты, снова запрашиваю код ревью @kolyanch

2022-03-07 12:14 UTC, kolyanch commented on Lab1/Repository/Repository.cs
> +        private List<AbstractMatrix> data;
Сделайте данное поле readonly

2022-03-07 12:15 UTC, kolyanch commented on Lab1/Repository/Repository.cs
> +            { AnsiConsole.WriteException(e); }
В catch тоже переставить скобки и так во всем файле

2022-03-07 12:18 UTC, kolyanch requested changes
На данный момент, если файл matrices.xml не существует, то добавление в репозиторий не работает. Нужно обработать данную ситуацию в методе Dump.

Также проект с unit-тестами нужно либо доработать, либо целиком убрать. 

Далее "есть" в комментах писать не нужно

2022-03-07 13:24 UTC, Divanchik commented
Исправил, дописал тесты для методов классов матриц, нужно ли писать тесты для класса репозитория? @kolyanch

2022-03-07 14:25 UTC, kolyanch requested changes
На репозиторий тесты в данном случае можно не писать

2022-03-07 14:25 UTC, kolyanch commented on Lab1/Repository/Repository.cs
> +            }
Так не пойдет. Нужно отдельно отработать этот случай и не создавать пустой файл. Сейчас получается он создается, а потом ещё раз читается

2022-03-07 14:25 UTC, kolyanch commented on Lab1/Repository/Repository.cs
> +                AnsiConsole.WriteException(e);
Репозиторий нужно абстрагировать от знания об AnsiConsole. Лучше ловите исключения при использовании методов

2022-03-07 15:07 UTC, Divanchik commented
Исправил, запрашиваю код ревью @kolyanch

2022-03-07 17:03 UTC, kolyanch commented
Замечания не поправлены по сути. 

- В методе репозитория Load все равно происходит создание файла. От него вообще никак нельзя отказаться? Использовать пустой список матриц, если они вообще не вводились
- Репозиторий все ещё зависим от AnsiConsole

2022-03-07 17:20 UTC, Divanchik commented
А теперь? @kolyanch

2022-03-07 17:36 UTC, kolyanch commented
Стало лучше. Дополнительно matrices.xml вынесите в константу и используйте ее.  
Протестируйте приложение, а конкретно класс AddMatrixCommand на случай, если matrices.xml отсутствует и пользователь пытается ввести первую матрицу.

2022-03-07 17:45 UTC, Divanchik commented
Подправил и протестировал

2022-03-08 08:00 UTC, kolyanch requested changes

2022-03-08 08:00 UTC, kolyanch commented on Lab1/Commands/AddMatrixCommand.cs
> +            if (indIns < 0 || indIns > _data.Count - 1 && _data.Count > 1)
Очень странная проверка. 
Сейчас она звучит как: индекс вышел за границы, если пользователь ввёл отрицательный индекс элемента для вставки или индекс больше количества элементов, при условии что количество элементов два и больше. 

Условие выше тоже странное. Почему индекс спрашивается только при условии, что в коллекции уже как минимум 2 элемента?

Условия ввода должны быть:
- если в репозиторие ничего нет, индекс можно не спрашивать, считать его равным 0
- иначе спросить индекс и проверить, что он от 0 до количества элементов в коллекции
-

2022-03-08 08:11 UTC, Divanchik commented
Исправлено? @kolyanch

2022-03-08 08:54 UTC, kolyanch commented
Исправлено. Остался момент со значениями матриц. На текущий момент или всегда пустые - для BufferedMatrix все элементы равны 0, SparseMatrix всегда пуста. Нужно добавить возможность для пользователя либо ввода значений элементов матрицы, либо заполнения матрицы случайными числами

2022-03-10 17:39 UTC, Divanchik commented
Доработал, проверьте пожалуйста @kolyanch

2022-03-11 05:01 UTC, kolyanch requested changes
Нужно переделать ввод матрицы. Можете сделать даже вариант, когда элемент вводится через CommandSettings. Но тот вариант, что сейчас крайне неудобен для пользователя и мало чем отличается от ручного редактирования xml

2022-03-11 08:28 UTC, kolyanch requested changes

2022-03-11 08:28 UTC, kolyanch commented on Lab1/Commands/ModifyMatrixCommand.cs
> +            public double newValue {get; set;}
Нарушение правил именования свойств

2022-03-11 08:28 UTC, kolyanch commented on Lab1/Commands/ModifyMatrixCommand.cs
> +            // }
Удалить это

2022-03-11 09:14 UTC, kolyanch approved these changes

2022-03-11 09:15 UTC, closed without merging