All Done Чудилин 6312
itsec-labs/dotnet-1 pull request #18
Opened 2022-03-15 15:46 UTC by EraserH

Не смог только победить AnsiConsole, хотя я её установил, она нормально не работает. Поэтому сделал по-другому, менее красиво

2022-03-16 05:30 UTC, kolyanch requested changes

2022-03-16 05:30 UTC, kolyanch commented on src/Lab1/Lab1/Commands/OrganizedMenu/Menu.cs
> +    static class Menu
Лучше избавиться от этого класса. Функционал поместить в конкретные команды. Общее меню не обязательно

2022-03-16 05:30 UTC, kolyanch commented on src/Lab1/Lab1/Commands/OrganizedMenu/Menu.cs
> +                bool no_error = true;
Нарушение правил именования переменных

2022-03-16 05:30 UTC, kolyanch commented on src/Lab1/Lab1/Commands/OrganizedMenu/Menu.cs
> +            Function tmp;
Плохое имя для переменной

2022-03-16 05:30 UTC, kolyanch commented on src/Lab1/Lab1/Commands/OrganizedMenu/Menu.cs
> +                    return;*/
Вычистить лишние комменты

2022-03-16 05:30 UTC, kolyanch commented on src/Lab1/Lab1/Commands/OrganizedMenu/Menu.cs
> +                int first_index = Convert.ToInt32(input);
Нарушение правил именования переменных

2022-03-16 05:30 UTC, kolyanch commented on src/Lab1/Lab1/Commands/OrganizedMenu/Menu.cs
> +                var second_index = Convert.ToInt32(input);
Нарушение правил именования переменных

2022-03-16 05:30 UTC, kolyanch commented on src/Lab1/Lab1/Commands/OrganizedMenu/Menu.cs
> +            Console.WriteLine($"При x = {x} наибольшее значение принимает фукнция");
*функция

2022-03-16 05:30 UTC, kolyanch commented on src/Lab1/Lab1/Commands/OrganizedMenu/Menu.cs
> +            Console.WriteLine($"При x = {x} наибольшее значение принимает фукнция");
*функция

2022-03-16 05:30 UTC, kolyanch commented on src/Lab1/Lab1/Commands/OrganizedMenu/Menu.cs
> +            Console.WriteLine($"f({x}) = {maxFunc.getValue(x)}");
Что будет в данном случае, если репозиторий пуст?

2022-03-16 05:30 UTC, kolyanch commented on src/Lab1/Lab1/Commands/OrganizedMenu/Menu.cs
> +        public static void MainMenu(ref IFunctionsRepository functionRepository)
Почему везде ref?

2022-03-16 05:30 UTC, kolyanch commented on src/Lab1/Lab1/FunctionsRepository/IFunctionsRepository.cs
> +        public Function? GetMaxValueFunction(double x);
Зачем в данном случае нужен Nullable?

2022-03-16 05:30 UTC, kolyanch commented on src/Lab1/Lab1/FunctionsRepository/XMLFunctionsRepository.cs
> +        List<Function> lst;
Плохое название и нарушение правил именования

2022-03-16 05:30 UTC, kolyanch commented on src/Lab1/Lab1/FunctionsRepository/XMLFunctionsRepository.cs
> +        private bool ReadFile()
Зачем данный метод возвращает bool?

2022-03-16 05:30 UTC, kolyanch commented on src/Lab1/Lab1/FunctionsRepository/XMLFunctionsRepository.cs
> +        private bool WriteToFile()
Зачем метод возвращает bool?

Очистить код от лишних комментов

2022-03-16 05:30 UTC, kolyanch commented on src/Lab1/Lab1/Lab1.csproj
> +    <PackageReference Include="AnsiConsole" Version="0.2.0" />
Данный пакет используется только для .Net Framework, он не нужен

2022-03-16 05:30 UTC, kolyanch commented on src/Lab1/Lab1/Model/Function.cs
> +namespace Functions
Должен быть namespace Lab1.Model

2022-03-16 05:30 UTC, kolyanch commented on src/Lab1/Lab1/Model/Function.cs
> +        public abstract Function getDerivative();
Нарушение правил именования методов

2022-03-16 05:30 UTC, kolyanch commented on src/Lab1/Lab1/Model/Function.cs
> +            // то возвращаем true, если имена совпадают
О чем данный комментарий? Какой Person?

2022-03-16 05:30 UTC, kolyanch commented on src/Lab1/Lab1/Model/LogFunc.cs
> +namespace Functions
Должен быть namespace Lab1.Model

2022-03-16 09:19 UTC, EraserH commented on src/Lab1/Lab1/Model/Function.cs
> +            // то возвращаем true, если имена совпадают
не помню, откуда-то скопипастил

2022-03-16 09:22 UTC, EraserH commented on src/Lab1/Lab1/Commands/OrganizedMenu/Menu.cs
> +    static class Menu
я решил, что с меню удобнее: можно работать с коллекцией не только отдельными вызовами программы с аргументами, но и с функционалом программы целиком. То есть нужно, чтобы работать с программой можно было только так:
Lab1 add
Lab1 delete
и т.д.
?

2022-03-16 10:05 UTC, kolyanch commented on src/Lab1/Lab1/Commands/OrganizedMenu/Menu.cs
> +    static class Menu
Да, достаточно, чтобы с приложением можно было работать только через команды

2022-03-20 12:57 UTC, kolyanch requested changes
Не устранены некоторые замечания с предыдущего ревью 
+ добавил новые

2022-03-20 12:57 UTC, kolyanch commented on src/Lab1/Lab1/Commands/CountFunctionCommand.cs
> +        private void OwnCount(ref IFunctionsRepository _functionRepository)
Нарушение правил именования аргументов методов. Почему ref?

2022-03-20 12:57 UTC, kolyanch commented on src/Lab1/Lab1/Commands/CountFunctionCommand.cs
> +            Console.WriteLine($"При x = {x} наибольшее значение принимает фукнция");
*функция

2022-03-20 12:57 UTC, kolyanch commented on src/Lab1/Lab1/Commands/CountFunctionCommand.cs
> +        private void LinqCount(ref IFunctionsRepository _functionRepository)
Нарушение правил именования аргументов методов. Почему ref?

2022-03-20 12:57 UTC, kolyanch commented on src/Lab1/Lab1/Commands/CountFunctionCommand.cs
> +            Console.WriteLine($"При x = {x} наибольшее значение принимает фукнция");
*функция

2022-03-20 12:57 UTC, kolyanch commented on src/Lab1/Lab1/Commands/DeleteFunctionCommand.cs
> +            Function tmp;
Плохое наименование переменной

2022-03-20 12:57 UTC, kolyanch commented on src/Lab1/Lab1/FunctionsRepository/IFunctionsRepository.cs
> +        string ToString();
Зачем в интерфейсе ToString?

2022-03-20 12:57 UTC, kolyanch commented on src/Lab1/Lab1/FunctionsRepository/XMLFunctionsRepository.cs
> +            return;
Убрать return

2022-03-20 12:57 UTC, kolyanch commented on src/Lab1/Lab1/FunctionsRepository/XMLFunctionsRepository.cs
> +            return;
Убрать return

2022-03-20 12:57 UTC, kolyanch commented on src/Lab1/Lab1/Model/ConstFunc.cs
> +        public ConstFunc(double _coef)
Нарушение правил именования аргументов

2022-03-20 12:57 UTC, kolyanch commented on src/Lab1/Lab1/Model/DerLog.cs
> +        public DerLog(double value, double _coef = 1)
Нарушение правил именования аргументов

2022-03-20 12:57 UTC, kolyanch commented on src/Lab1/Lab1/Model/ExpoFunc.cs
> +        public ExpoFunc(double value, double _coef = 1)
Нарушение правил именования аргументов

2022-03-20 12:57 UTC, kolyanch commented on src/Lab1/Lab1/Model/LogFunc.cs
> +        public LogFunc(double value, double _coef = 1)
Нарушение правил именования аргументов

2022-03-20 12:57 UTC, kolyanch commented on src/Lab1/Lab1/Model/PowerFunc.cs
> +        public PowerFunc(double value, double _coef = 1)
Нарушение правил именования аргументов

2022-03-20 17:20 UTC, EraserH commented on src/Lab1/Lab1/Lab1.csproj
> +    <PackageReference Include="AnsiConsole" Version="0.2.0" />
у меня этот файл в VS не открывается почему-то. А что здесь подразумевается под пакетом и что нужно убрать? 13 строку где добавляется AnsiConsole?

2022-03-21 07:27 UTC, kolyanch commented
Осталось замечание с полем lst в классе XMLFunctionsRepository

2022-03-21 09:39 UTC, kolyanch approved these changes

2022-03-21 09:39 UTC, closed without merging