Pull-reqest fist
itsec-labs/dotnet-1 pull request #2
Opened 2022-02-17 13:41 UTC by SirlLizz

Project of Moiseev Ilya from Group 6312

2022-02-17 14:58 UTC, kolyanch requested changes
Много опечаток в проекте.
Пока не реализован функционал из задания:
Предоставить возможность вычисления суммарного объёма всех фигур в контейнере (считать, что фигуры не пересекаются друг с другом). Вычисление организовать двумя способами: своим кодом и с использованием System.Linq.

Использование фасада и MVC вызывает вопросы.

2022-02-17 14:58 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/controller/ConsoleController.cs
> +        public void OpenFile(String path)
Исправить на string

2022-02-17 14:58 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/controller/ConsoleController.cs
> +            catch (Exception ex)
Переменная ex нигде не используется. Либо убрать её, либо использовать при выводе сообщения

2022-02-17 14:58 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/controller/ConsoleController.cs
> +        public void SaveFile(String path)
Исправить на string

2022-02-17 14:58 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/controller/ConsoleController.cs
> +        }
Почему бы вместо всех этих методов не сделать _figures публичным property?
Метод SetFigures к тому же нигде не используется

2022-02-17 14:58 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/controller/ConsoleController.cs
> +            return false;
Переделать:
- сразу проверять if (_figures == null)
- сложную проверку с возвратом true заменить одним return

2022-02-17 14:58 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/model/figures/Point.cs
> +namespace VolumetricFigures.model.figures
Namespace и папку переименовать. Привести к единому именованию:
- папка -> Figures
- namespace -> VolumetricFigures.Model.Figures

И так во всех файлах

2022-02-17 14:58 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/model/figures/Point.cs
> +        public double z { get; set; }
Нарушение правил именования для свойств. Сделать upper case

2022-02-17 14:58 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/model/figures/Point.cs
> +            this.z = z;
После изменения наименований свойств убрать this

2022-02-17 14:58 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/model/figures/RectangularCuboid.cs
> +        public Point _p2 { get; set; }
Нарушение правил именования свойств

2022-02-17 14:58 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/model/figures/RectangularCuboid.cs
> +        public double GetWidht()
Опечатка в названии метода

2022-02-17 14:58 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/model/figures/RectangularCuboid.cs
> +        public double GetHight()
Опечатка в названии метода

2022-02-17 14:58 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/model/figures/RectangularCuboid.cs
> +            return "1: " + _p1.ToString() + "2: " + _p2.ToString();
Вызов ToString() в данном случае не нужен

2022-02-17 14:58 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/model/figures/RectangularCuboid.cs
> +            return rectangularCuboid._p1.Equals(_p1) &&
Тут будет NullReferenceExсeption, если obj не RectangularCuboid

2022-02-17 14:58 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/model/figures/RectangularCuboid.cs
> +            return _p1.GetHashCode() ^ _p2.GetHashCode();
https://docs.microsoft.com/en-us/dotnet/api/system.object.gethashcode?redirectedfrom=MSDN&view=net-6.0#notes-to-inheritors

Нарушение: You can compute the hash code from fields that are not mutable
И так во всех классах

2022-02-17 14:58 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/model/figures/Sphere.cs
> +        public double _radius { get; set; }
Нарушение правил именования свойств

2022-02-17 14:58 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/model/figures/Sphere.cs
> +            return "Centre: " + _centre.ToString() + "Radius: " + _radius;
ToString() в данном случае не нужен

2022-02-17 14:58 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/model/figures/Сylinder.cs
> +            return "Centre: " + _centreFoundation.ToString() + "Radius: " + _radius + "\nHeight: " + _height;
ToString() в данном случае не нужен

2022-02-17 14:58 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/model/Counting.cs
> +    public abstract class Counting
Как перевести в данном случае Counting? Подсчет? Расчет? Может лучше переименовать?

2022-02-17 14:58 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/view/ConsoleView.cs
> +                                String pathSave = Console.ReadLine();
Используйте string

2022-02-17 19:27 UTC, SirlLizz commented
По mvc вы говорили, что много зависимости во вью от модели, а как мне тогда лучше разбить вьюшку на команды лучше? На каждый свич по свое команде или на каждый кейс все же по команде тоже делать?

2022-02-17 19:33 UTC, SirlLizz commented
Dependency я добавлю чуть позже, пока не успеваю с ним разобраться. И вопрос не по коду - Руслан Романович нам говорил, что по этому предмету будет введена бальная система, если не секрет, можете, пожалуйста, объяснить, как она будет работать в рамках лабораторных работ

2022-02-18 05:58 UTC, kolyanch commented
> По mvc вы говорили, что много зависимости во вью от модели, а как мне тогда лучше разбить вьюшку на команды лучше? На каждый свич по свое команде или на каждый кейс все же по команде тоже делать?

Свитч на команды вообще можно убрать, правильный образом их зарегистрировав. Кейсы на разные типы фигур останутся, от них сложно избавиться. Если вы хотите следовать концепции MVC, то по хорошему для каждой модели должен быть набор View - один View для ввода данных, один View для отображения данных и т.д. Контроллер соответственно должен возвращать View для конкретных кейсов. Но для данной задачи возможно это будет overengineering. И может быть проще все-таки будет остаться на инфраструктуре Spectre.Console.

Упрощенный пример команд тут: https://github.com/kolyanch/dotnet-1/blob/main/src/Lab1/Lab1/Commands/GetAllFeaturesCommand.cs

Регистрация команд и DI: 
https://github.com/kolyanch/dotnet-1/blob/main/src/Lab1/Lab1/Program.cs

2022-02-18 06:01 UTC, kolyanch commented
> Dependency я добавлю чуть позже, пока не успеваю с ним разобраться. И вопрос не по коду - Руслан Романович нам говорил, что по этому предмету будет введена бальная система, если не секрет, можете, пожалуйста, объяснить, как она будет работать в рамках лабораторных работ

Критерии оценивания [тут](https://github.com/itsec-labs/dotnet-1#%D0%BA%D1%80%D0%B8%D1%82%D0%B5%D1%80%D0%B8%D0%B8-%D0%BE%D1%86%D0%B5%D0%BD%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)

У вас к примеру уже доп. баллы за:
- первый пулл-реквест
- попытку выйти за рамки (MVC)
- первый работающий код

2022-02-19 10:44 UTC, SirlLizz commented
Я добавил команды и DI по вашему видео, можно повторный ревью?

2022-02-19 10:47 UTC, SirlLizz commented
Гит засунул контроллер в пакет controller, так как такой уже был, а интерфейс - в новый пакет Controller
![image](https://user-images.githubusercontent.com/73231157/154797678-c40d5638-8b0c-4e1c-aafe-c813b0e42ede.png)

2022-02-19 12:55 UTC, kolyanch requested changes
Остались неустраненные замечания с предыдущего ревью.
Плюс ещё два

2022-02-19 12:55 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/model/figures/Сylinder.cs
> +                cylinder.Height == Height;
Выровнять разметку кода, что-то съехало

2022-02-19 12:55 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/view/ConsoleView.cs
> +    public class ConsoleView
В текущей версии не понятно зачем нужен этот класс, если View - это по сути класс Program

2022-02-19 13:10 UTC, SirlLizz commented
View я использую только для того, чтоб program оставался только точкой входа в программу, а логика выполнялась уже где-то далее

2022-02-19 13:34 UTC, SirlLizz commented
А почему у Cylinder нарушение правил именования свойств? Я же их все переименовал
И у RectangularCuboid есть catch на NullReferenceExсeption

2022-02-19 13:42 UTC, SirlLizz commented
Откорректированый вроде код запушил

2022-02-19 13:58 UTC, kolyanch commented
> А почему у Cylinder нарушение правил именования свойств? Я же их все переименовал И у RectangularCuboid есть catch на NullReferenceExсeption

Сейчас код на rethrow любого исключения в NullReferenceExсeption - это не правильно.
try/catch в данном случае не нужен. У вас метод сравнения объектов, какой результат должен быть, если параллелепипед сравнивается со сферой? NullReferenceExсeption?

2022-02-19 13:58 UTC, kolyanch commented
Также после последних изменений код должен перестать компилироваться

2022-02-19 14:20 UTC, SirlLizz commented
Тогда для возврата HashCode использовать просто return GetHashCode()?

2022-02-19 14:22 UTC, SirlLizz commented
Или конструкцию return HashCode.Combine<Point, Point>(P1, P2)?

2022-02-19 14:31 UTC, kolyanch commented
Нарушение: You can compute the hash code from fields that are not mutable

Вы либо делаете поля/свойства иммутабельными, либо оставляете как есть сейчас - метод GetHashCode не перегружается, используется реализация по умолчанию на основе ссылок

2022-02-19 14:58 UTC, SirlLizz commented
В шарпе же на данный момент нет ключевого слова immutable?
Достаточно будет сделать свойства неизменяемыми?
public double Radius { get; private set; }

2022-02-19 16:29 UTC, kolyanch commented
> В шарпе же на данный момент нет ключевого слова immutable? Достаточно будет сделать свойства неизменяемыми? public double Radius { get; private set; }

Ключевого слова immutable нет и не будет.
В случае приватного сеттера перестанет работать десериализация объектов. Поэтому данный вариант не подходит. Используйте init вместо set

2022-02-19 16:52 UTC, SirlLizz commented
Вроде теперь правильно, извините, что так туплю

2022-02-20 08:39 UTC, SirlLizz commented
Есть еще какие-то замечания?

2022-02-20 11:01 UTC, kolyanch requested changes
На данный момент данные введенные или измененные через команды не возможно сохранить в файл. Необходимо обеспечить, чтобы при запуске программы данные автоматически читались в память, а при завершении сохранялись на диск

2022-02-20 15:17 UTC, SirlLizz commented
Изменил

2022-02-20 15:29 UTC, kolyanch requested changes

2022-02-20 15:29 UTC, kolyanch commented on src/VolumetricFigures/VolumetricFigures/model/figures/RectangularCuboid.cs
> +            if ((obj != null) && obj is RectangularCuboid)
Нужно ещё упростить.
Проверка на null в данном случае уже не нужна, так как используется проверка на конкретный тип.
Объявление переменной rectangularCuboid совместите с проверкой is:
```C#
if (obj is RectangularCuboid rectangularCuboid)
```

И так во всех файлах

2022-02-20 16:03 UTC, SirlLizz commented
Изменил

2022-02-20 16:40 UTC, kolyanch approved these changes

2022-02-20 16:42 UTC, closed without merging