Промышленное программирование. Проект № 1
itsec-labs/dotnet-1 pull request #23
Opened 2022-03-22 06:38 UTC by VladaHaustova

2022-03-22 07:56 UTC, kolyanch requested changes

2022-03-22 07:56 UTC, kolyanch commented on src/Lab1/Lab1/Commands/AddMatrixCommand.cs
> +            if (_matricesRepository.GetMatrices().Count() == 0)
Используйте метод Any вместо Count

2022-03-22 07:56 UTC, kolyanch commented on src/Lab1/Lab1/Commands/AddMatrixCommand.cs
> +            var index = -1;
Зачем нужна данная инициализация?

2022-03-22 07:56 UTC, kolyanch commented on src/Lab1/Lab1/Commands/AddMatrixCommand.cs
> +            } while (index > _matricesRepository.GetMatrices().Count());
Используйте свойство Count вместо метода

2022-03-22 07:56 UTC, kolyanch commented on src/Lab1/Lab1/Commands/CompareMatricesCommand.cs
> +            var index2 = -1;
Инициализация не нужна

2022-03-22 07:56 UTC, kolyanch commented on src/Lab1/Lab1/Commands/CompareMatricesCommand.cs
> +            } while (index1 >= _matricesRepository.GetMatrices().Count());
Используйте свойство Count, а не метод

2022-03-22 07:56 UTC, kolyanch commented on src/Lab1/Lab1/Commands/CompareMatricesCommand.cs
> +            } while (index2 >= _matricesRepository.GetMatrices().Count());
Используйте свойство Count, а не метод

2022-03-22 07:56 UTC, kolyanch commented on src/Lab1/Lab1/Commands/CompareMatricesCommand.cs
> +                AnsiConsole.MarkupLine($"[red]Матрицы не равны[/]");
Воспользуйтесь тернарным оператором для аргумента метода MarkupLine. Зачем в строках $ ?

2022-03-22 07:56 UTC, kolyanch commented on src/Lab1/Lab1/Commands/RemoveMatrixCommand.cs
> +    public class RemoveMatrixCommand : Command<RemoveMatrixCommand.RemoveMatrixSettings>
Замечания идентичны другим коммандам - Count, -1

2022-03-22 07:56 UTC, kolyanch commented on src/Lab1/Lab1/Model/BufferedMatrix.cs
> +        public double[][] _matrix { get; init; }
Нарушение правил именования свойств

2022-03-22 07:56 UTC, kolyanch commented on src/Lab1/Lab1/Model/BufferedMatrix.cs
> +                    hashCode = hashCode * _matrix.GetLength(0);
Используйте оператор *=

2022-03-22 07:56 UTC, kolyanch commented on src/Lab1/Lab1/Model/Matrix.cs
> +        public override abstract int GetHashCode();
Нестандартный порядок модификаторов. Обычно используется порядок public abstract override

2022-03-22 07:56 UTC, kolyanch commented on src/Lab1/Lab1/Model/SparseMatrix.cs
> +        public Dictionary<Tuple<int, int>, double> _matrix;
Нарушение правил именования свойств

2022-03-22 07:56 UTC, kolyanch commented on src/Lab1/Lab1/Model/SparseMatrix.cs
> +                hashCode = hashCode * elem.GetHashCode();
Используйте оператор *=

2022-03-22 07:56 UTC, kolyanch commented on src/Lab1/Lab1/Model/SparseMatrix.cs
> +            foreach (var ((i, j), elem) in _matrix)
Для вычисления хэш-кода используется мутабельное публичное свойство

2022-03-22 07:56 UTC, kolyanch commented on src/Lab1/Lab1/Program.cs
> +using Lab1.Commands;
Удалить неиспользуемые using

2022-03-22 07:56 UTC, kolyanch commented on src/Lab1/Lab1/Repository/XmlMatricesRepository.cs
> +                            _matrices = new List<Matrix>();
Воспользуйтесь оператором ??=

2022-03-22 07:56 UTC, kolyanch commented on src/Lab1/Lab1/Repository/XmlMatricesRepository.cs
> +            for (var i = 0; i < _matrices.Count(); i++)
Используйте свойство Count, а не метод

2022-03-22 11:48 UTC, VladaHaustova commented on src/Lab1/Lab1/Commands/AddMatrixCommand.cs
> +            if (_matricesRepository.GetMatrices().Count() == 0)
Что за метод Any?

2022-03-22 11:50 UTC, kolyanch commented on src/Lab1/Lab1/Commands/AddMatrixCommand.cs
> +            if (_matricesRepository.GetMatrices().Count() == 0)
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.any?view=net-5.0

2022-03-22 14:54 UTC, kolyanch commented
После правок перестало работать чтение данных из xml

2022-03-22 16:50 UTC, kolyanch commented
Необходимо поправить ToString() у BufferedMatrix. Сейчас все выглядит так:
![image](https://user-images.githubusercontent.com/73119715/159532677-1fe48fd0-44a6-45b2-8094-310587790593.png)

Добавить пробелов

2022-03-22 16:54 UTC, kolyanch commented
Также необходимо добавить команду, реализующую определение матрицы с наименьшей нормой максимума модуля - пункт задания

2022-03-23 04:08 UTC, kolyanch approved these changes

2022-03-23 04:09 UTC, closed without merging