Final version
itsec-labs/dotnet-1 pull request #3
Opened 2022-02-23 22:02 UTC by RomanShafranyuk

К основной реализации добавлена реализация тестов иерархии классов

2022-02-24 04:57 UTC, kolyanch requested changes
Необходимо небольшие доделки.

Для выполнения unit-тестирования необходимо использовать: https://xunit.net/
Тесты переделать, там не долго

2022-02-24 04:57 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Commands/AddOperation.cs
> +                AnsiConsole.MarkupLine($"[orange]Неизвестный тип фигуры: {operationType}[/]");
Некорректное сообщение. В данном случае operationType всегда null, что следует из условия if

2022-02-24 04:57 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Commands/AddOperation.cs
> +            var text_insert = new TextPrompt<int>("[darkslategray3]Введите индекс, куда хотите вставить операцию: [/]");
Нарушение правил именования переменных

2022-02-24 04:57 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Commands/ComparingOperationsCommand.cs
> +            int index_lhs = AnsiConsole.Prompt(text1);
Нарушение правил именования переменных

2022-02-24 04:57 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Commands/ComparingOperationsCommand.cs
> +            int index_rhs = AnsiConsole.Prompt(text2);
Нарушение правил именования переменных

2022-02-24 04:57 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Commands/GetAllOperationsCommand.cs
> +            for (var i = 0; i < operations.Count(); ++i)
Используйте свойство Count, а не метод

2022-02-24 04:57 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Commands/GetAllOperationsCommand.cs
> +            if (operations.Count() > 10)
Используйте свойство Count, а не метод

2022-02-24 04:57 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Commands/GetAllOperationsCommand.cs
> +                table.AddRow($"[mediumpurple2_1]{operations[i].GetType().Name}[/]", $"[skyblue1]{operations[i].ToString()}[/]", $"[seagreen1_1]{operations[i].GetResult().ToString()}[/]");
Вызов ToString в данном случае не нужен

2022-02-24 04:57 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Commands/ComparingOperationsCommand.cs
> +            int index_rhs = AnsiConsole.Prompt(text2);
Нарушение правил именования переменных

2022-02-24 04:57 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Commands/ComparingOperationsCommand.cs
> +            int index_lhs = AnsiConsole.Prompt(text1);
Нарушение правил именования переменных

2022-02-24 04:57 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Commands/RemoveOperationCommand.cs
> +            int index_delete = AnsiConsole.Prompt(text_delete);
Нарушение правил именования переменных

2022-02-24 04:57 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Models/Operation.cs
> +        public abstract int GetResult();
Данный метод должен принимать 2 аргумента.
От использования структуры Numbers лучше отказаться. Общий интерфейс должен содержать один метод:
2 числа на входе, одно на выходе. 

Это приведет к необходимости переделать методы Equals и GetHashCode во всех классах

2022-02-24 04:57 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Program.cs
> +            IOperationRepository operations_repository = new XmlOperationRepository();
Данная переменная нигде не используется

2022-02-24 04:57 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Repositories/IOperationRepository.cs
> +        public bool CompareOperations(int lhs_index, int rhs_index);
Нарушение правил именования аргументов методов

2022-02-24 04:57 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Repositories/XmlOperationRepository.cs
> +            }
Почему не используется метод Clear()?

2022-02-24 04:57 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Repositories/XmlOperationRepository.cs
> +            foreach (var operation_type in _operations)
Нарушение правил именования переменных

2022-02-24 04:57 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Repositories/XmlOperationRepository.cs
> +        public void PrintCollection()
Данный метод нигде не используется. Удалить его из класса и интерфейса

2022-02-24 04:57 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Repositories/XmlOperationRepository.cs
> +                    continue;
В чем смысл данного кода?

2022-02-24 04:57 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Repositories/XmlOperationRepository.cs
> +            AnsiConsole.MarkupLine("[orange1]Минимальная операция, найденная циклом: [/]" + min.ToString()); // сделать покрасивее
Вызов ToString в данном случае не нужен

2022-02-24 17:34 UTC, RomanShafranyuk reviewed
Замечания исправлены. Прошу повторный code rewiev

2022-02-25 07:52 UTC, kolyanch commented
2 замечания из первого review не устранены

2022-02-25 08:12 UTC, RomanShafranyuk commented on Src/Binary_operations/Binary_operations/Models/Operation.cs
> +        public abstract int GetResult();
Тогда возникает вопрос, что делать с методами, которые ищут минимальный элемент по результату. Не совсем понятно, что нужно будет туда передавать.

2022-02-25 08:47 UTC, RomanShafranyuk commented on Src/Binary_operations/Binary_operations/Models/Operation.cs
> +        public abstract int GetResult();
И еще такой вопрос: могут ли быть поля в абстрактном классе?

2022-02-25 09:00 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Models/Operation.cs
> +        public abstract int GetResult();
> Тогда возникает вопрос, что делать с методами, которые ищут минимальный элемент по результату. Не совсем понятно, что нужно будет туда передавать.

В методы расчета минимума необходимо передать 2 аргумента, которые должен ввести пользователь. 
Далее необходимо пробежаться по всем операциям и вычислить для данных аргументов

> И еще такой вопрос: могут ли быть поля в абстрактном классе?

Могут. В том числе виртуальными/абстрактными, если реализованы как property

2022-02-25 09:28 UTC, RomanShafranyuk commented
Исправлены незамеченные мною ранее 2 замечания. Прошу повторный code_review

2022-02-25 10:52 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Models/Operation.cs
> +      public int Rhs { get; set; }
Непонятно зачем нужны данные свойства. Для выполнения операции вполне достаточно одного метода ниже

2022-02-25 11:36 UTC, RomanShafranyuk commented on Src/Binary_operations/Binary_operations/Models/Operation.cs
> +      public int Rhs { get; set; }
Для передачи параметров в GetResult() в печать результатов и поиск минимального элемента

2022-02-25 11:56 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Models/Operation.cs
> +      public int Rhs { get; set; }
Для печати достаточно вывести название операции, а не значение для определенных аргументов. 
Поиск минимального элемента должен проходить по схеме:
- пользователь вводит 2 аргумента в консольном приложении
- определяются все возможные операции в репозитории
- для всех операций через метод GetResult определяется значение для данных аргументов
- находится минимальное значение среди вычисленных 

Самим операциям (как классам) при этом знать об аргументах не нужно. Аргументы придут как параметры метода GetResult

2022-02-25 12:17 UTC, RomanShafranyuk commented on Src/Binary_operations/Binary_operations/Models/Operation.cs
> +      public int Rhs { get; set; }
Т.е. поля и свойства в классе в принципе не нужны?

2022-02-25 12:19 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Models/Operation.cs
> +      public int Rhs { get; set; }
Да, классы будут содержать только методы. 
В xml при сериализации будут попадать тоже только названия операций, больше там хранить нечего

2022-02-25 12:19 UTC, RomanShafranyuk commented on Src/Binary_operations/Binary_operations/Models/Operation.cs
> +      public int Rhs { get; set; }
И в таблице будет 2 колонке: название операции и числа, над которыми операция проводится?

2022-02-25 12:24 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Models/Operation.cs
> +      public int Rhs { get; set; }
При выводе в консоль всех операций только названия методов, аргументов и результата вычисления не будет

2022-02-25 12:45 UTC, RomanShafranyuk commented on Src/Binary_operations/Binary_operations/Models/Operation.cs
> +      public int Rhs { get; set; }
Т.е.  для определенных аргументов (чисел) нужно понять, какая  из 5 операций является наименьшей? И еще уточнение: получается что в коллекции будет храниться не больше 5 элементов (раз нет чисел, то нет смысла 2 раза вносить какую то операцию, например сложение)? И тогда получается, что нет смысла в следующем условии: если операций больше 10, то выводить ... ?

2022-02-25 12:53 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Models/Operation.cs
> +      public int Rhs { get; set; }
Вы через команду AddOperationCommand добавляете указанные пользователем операции в репозиторий. Их может быть больше или меньше 5, т.е. пользователь в теории может продублировать одну и ту же операцию или указать не все. После этого через команду MinOperation вы должны спросить у пользователя 2 аргумента и вычислить минимум из результата вычисления по всем добавленным им операциям.

Если хотите можете также обеспечить уникальность типа операции в репозитории. Тогда у вас всегда будет не более 5 объектов в коллекции. Для выбора можно использовать мультиселект: https://spectreconsole.net/prompts/multiselection

2022-02-25 14:46 UTC, RomanShafranyuk commented on Src/Binary_operations/Binary_operations/Models/Operation.cs
> +      public int Rhs { get; set; }
Есть еще следующие вопросы (написал текст и забыл отправить 😄)
Также возникают вопросы в следующем:
1. Что должен будет возвращать перегруженный метод ToString()?
2.  Какова реализация Equals? Просто сравнение на типы? Но тогда смысл этому же опять отпадает, исходя из предыдущего комментария
3.  Немного непонятна реализация HashCode()

2022-02-26 06:07 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Models/Operation.cs
> +      public int Rhs { get; set; }
1. ToString() должен вернуть название операции
2. Equals должен сравнивать типы операций
3. Возьмите хэш от GetType()

2022-02-26 13:22 UTC, RomanShafranyuk commented
Замечания исправлены. Прошу повторный code review

2022-02-26 14:16 UTC, kolyanch requested changes
Нужно ещё немного подправить

2022-02-26 14:16 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Models/Addition.cs
> +            return this.GetType().Name;
this в данном случае не нужен. И так во всех классах модели

2022-02-26 14:16 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Models/Addition.cs
> +            return false;
Преобразовать в одну строчку - сразу return. И так во всех классах модели

2022-02-26 14:16 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Models/Addition.cs
> +            return this.GetType().GetHashCode();
this в данном случае не нужен. И так во всех классах модели

2022-02-26 14:16 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Repositories/XmlOperationRepository.cs
> +            AnsiConsole.MarkupLine($"[wheat1]Минимальная операция, найденная с помощью Linq: {minOperation}. Значение {_operations.Min(operation => operation.GetResult(left,right))}  [/] ");
Репозиторий как класс не должен знать ничего про AnsiConsole. Он должен быть абстрагирован от конкретного способа ввода или визуализации данных. Поэтому данный метод должен принимать 2 аргумента, код по вводу и выводу нужно перенести в соответствующую команду. А сам метод должен возвращать данные для вывода в консоль

2022-02-26 14:39 UTC, RomanShafranyuk commented on Src/Binary_operations/Binary_operations/Repositories/XmlOperationRepository.cs
> +            AnsiConsole.MarkupLine($"[wheat1]Минимальная операция, найденная с помощью Linq: {minOperation}. Значение {_operations.Min(operation => operation.GetResult(left,right))}  [/] ");
Метод min должен возвращать название операции?

2022-02-26 14:41 UTC, kolyanch commented on Src/Binary_operations/Binary_operations/Repositories/XmlOperationRepository.cs
> +            AnsiConsole.MarkupLine($"[wheat1]Минимальная операция, найденная с помощью Linq: {minOperation}. Значение {_operations.Min(operation => operation.GetResult(left,right))}  [/] ");
Можно да, только название

2022-02-26 17:45 UTC, RomanShafranyuk commented
Очередные исправления проведены.  Прошу очередной code review)

2022-02-26 18:10 UTC, kolyanch approved these changes

2022-02-26 18:10 UTC, closed without merging