Лаба 1
itsec-labs/dotnet-1 pull request #33
Opened 2022-05-06 20:15 UTC by SauvageDior

рабочая версия

2022-05-08 09:05 UTC, navna requested changes
1. Директорию `module` со всем содержимым удалить.
2. **Правила именования пространств имён нарушены.**
    - Любое пространство имён должно начинаться с большой буквы.
    - Названия директорий (папок) должны соответствовать пространствам имён (тоже должны начинаться с большой буквы).
    - Название csproj-файла тоже должно быть с большой буквы (во-первых, для согласованности; во-вторых корневое пространство имён по умолчанию определяется по названию этого файла).
    - При изменении названия csproj убедитесь, что в sln путь останется корректным в плане регистрозависимости (хоть под Windows пути и регистронезависимые, но под Linux это не так).
3. **Правила именования методов нарушены.** Все они должны начинаться с большой буквы.
4. В проекте включить поддержку nullable и, **вдумываясь**, выправить все предупреждения компилятора.
5. Атрибут [Serializable] удалить у любого конкретного класса-функции.
6. Все лишние пустые строки удалить по всему проекту целиком (это можно сделать автоматом, настроив жёсткие правила форматирования - раз своими руками вы это делать, видимо, не в состоянии). Пустые строки должны быть:
    - Глобально в файле:
      - обязательно: между блоком `using` и namespace;
      - опционально: между блоками `using`, соответствующим разным пакетам;
    - Внутри класса:
      - обязательно: между членами различного типа (например, между полями и свойствами);
      - обязательно: между членами одного типа, если один из них занимает несколько строк (например, между любыми методами, т. к. каждый из них занимает минимум 4 строки);
      - опционально: между свойствами, объявление которых занимает одну строку.
    - Если код метода большой, допускается визуально разделить его пустыми строками на несколько секций.
    - Во всех иных случаях наличие пустой строки недопустимо.
    - Больше одной пустой строки подряд нигде не допускается.
7. После всех исправлений все `using` вычистить и упорядочить (в принципе, это делается настроенным автоформаттером одновременно с п. 6).
8. Почему у вас в зависимостях есть `Microsoft.Extensions.CommandLineUtils`? Какой функционал вы из неё используете (или использовали)? Это не риторический вопрос, в обязательном порядке жду на него ответа. Ответ `включил по ошибке` не принимается ввиду его очевидной ложности. Или вы реально обосновываете его использование (в виде указания кода, который его использует или ссылки на коммит, в котором эта библиотека использовалась в вашем коде ранее), или признавайте факт списывания.

Знаете, вот с учётом всех замечаний по коду начинать с вашей стороны выёживаться (путем использования контроллеров, которые нигде и не используются; путем использования суффикса DAO, который не применим к используемой схеме именования) - это верх наглости. Либо, наиболее вероятный сценарий, вы всё скатали, не удосужившись даже разобраться (!!!). Ремарка в текущем абзаце риторическая, она всего лишь выражает моё глубокое разочарование, комментариев/оправданий/ответа от вас она не подразумевает.

2022-05-08 10:39 UTC, SauvageDior commented
На 8 пункт ответ очень простой. Внутри Microsoft.Extensions.CommandLineUtils как вы знаете лежит класс ansiconsole, и когда я подключал spectre я его в тупую писал без подключения зависимостей (ну как на питоне в надежде что он сам подгрузится), а компилятор соответственно не понимал что это за ansiconsole и по нажатию на кнопку подсказки (желтая лампочка которая), он предлагал загрузить эту командную строку. Вот поэтому она там и лежит, хотя и никак не используется. Потом уже когда до меня дошло что spectre компилятор так и не додумается найти я его вручную подключил, а на командную строку эту уже не обратил внимания и не придал значения. Ну а в качестве ссылки на код где она используется любую строку можно приложить где есть ansiconsole, поэтому она включена не по ошибке, а т.к. компилятор просто не понял какой это класс и сам подгрузил эту зависимость.
 По поводу DAO тоже могу обосновать почему я его использовал в наименовании, но я с вами согласен что он не корректно используется в данном случае.

2022-05-08 17:24 UTC, navna commented
> Ну а в качестве ссылки на код где она используется любую строку можно приложить где есть ansiconsole, поэтому она включена не по ошибке, а т.к. компилятор просто не понял какой это класс и сам подгрузил эту зависимость.

Этот текст не соответствует ничему из того, что вы так подробно разъясняли до него. У вас везде используется `AnsiConsole` из `Spectre.Console`, а не из `Microsoft.Extensions.CommandLineUtils` и это разные классы! Поэтому данный пакет не используется **нигде** и его нужно удалить.

2022-05-08 17:33 UTC, navna requested changes
Вы вообще замечания читаете или нет? Читайте их внимательнее!
1. Класс репозитория всё еще назван некорретно.
2. Пустые строки всё еще применяются несогласованно.

Дальше смотреть не стал.
1. Не спешите.
2. Проверяйте всё тщательнее.
3. Не смейте тратить моё время впустую (как вы это сделали с запросом повторного ревью), пока не исправили методично шаг за шагом все замечания.
4. Если вы пытаетесь успеть к среде - можете уже не пытаться. Особенно, если продолжите в том же духе.
5. Тему на проект (2 и 3 лаба) можно согласовать (и, соответственно, начать делать) прямо сейчас, не дожидаясь сдачи первой лабы. На тот случай, если вы не в курсе.

2022-05-08 17:43 UTC, SauvageDior commented
Ну так я и говорю что AnsiConsole из CommandLine нигде не используется, а в зависимостях эта библиотека появилась не потому что я ее для чего-то подключал, а потому что среда сама ее предложила загрузить при наведении на AnsiConsole. Грубо говоря я написал строчку кода: var functionType = AnsiConsole...(...) и по привычке просто навел на нее мышкой и нажал первую попавшуюся библиотеку подключить из предложенных средой. Потом когда вылетела ошибка, что метод Promt не содержится в классе AnsiConsole, я понял что это другой класс вообще, но уже не стал удалять библиотеку из зависимостей и подключил нужную Spectre. 
Остальные ошибки исправлю, просто авто-форматирование кода сделал, не проверил что изменилось и отправил
И вот еще вопрос на счет полей в функциях, я просто поспешил и ничего не сделал умного, грубо говоря внутри классов лежит одно поле Value везде и все. Можно ли так оставить? или если надо переделать то как лучше: в каждом классе отдельно поля добавить ( к примеру в степенной функции основание и степень) или отдельно структуру какую-нибудь для хранения значений функции универсальную для всех классов?

2022-05-09 10:38 UTC, navna commented
В каждом классе завести индивидуально. Только свойства, а не поля.

2022-05-20 15:28 UTC, navna requested changes
1. Объясните назначение свойства `Value` в любом классе функции, кроме `Const`, если это свойство никак не участвует в вычислении значения функции? Удалить отовсюду вкупе с соответствующими конструкторами.
2. Рассмотрим функцию логарифма. Вы знаете, что производная логарифма - это не логарифм? Тогда какого чёрта у вас происходит в методе вычисления производной функции?
3. Аналогично со степенной функцией.
4. `EXP` и любые другие захардкоженные константы отовсюду удалить. Использовать предопределённые константы из класса `System.Math`.

Вы пишете основу системы компьютерной алгебры для символьных вычислений - на случай, если до вас так и не дошёл смысл вашего варианта. Но чтобы вы не пытались воплотить, это всё равно спроектировано неверно (хотя бы ввиду замечаний 1-3) Посмотрите на базовый класс функции (он спроектирован более-менее) и попробуйте переосмыслить всё то, что вы понаписали.

2022-06-07 06:49 UTC, navna commented
Время истекло. Работу не засчитываю. Теперь сдавайте всё очно по договорённости.

2022-06-07 06:49 UTC, closed without merging